<?php

namespace app\admin\controller;

use think\Controller;
use think\Db;
use think\Request;
use think\Validate;

class Stayhome extends Controller
{
    public $code;
    public $validate;
    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
//        checkToken();
    }

    public function __construct(Request $request = null)
    {
        parent::__construct($request);
        $this->code=config("code");
        $this->validate=\validate('Stayhome');
    }

    /**
     * 显示资源列表
     *
     * @return \think\Response
     */
    public function index()
    {
        //
        $data=$this->request->get();
        if(isset($data['pages'])&&!empty($data['pages'])){
            $page=$data['pages'];
        }else{
            $page=1;
        }
        if(isset($data['limit'])&&!empty($data['limit'])){
            $limit=$data['limit'];
        }else{
            $limit=5;
        }
        $where=[];
        if(isset($data['scity'])&&!empty($data['scity'])){
            $where['scity']=$data["scity"];
        }
        if(isset($data['sname'])&&!empty($data['sname'])){
            $where['sname']=['sname',"%".$data["sname"]."%"];
        }

        $result=Db::table("stayhome")->field('sname,sdesc,sprice,sthumb,stag,ctime,sid')->where($where)->paginate($limit,false,['pages'=>$page]);
        $stayhome=$result->items();
        $total=$result->count();
        if($stayhome&&$total){
            return json([
                'code'=>$this->code['success'],
                'msg'=>'查询成功',
                'data'=>$stayhome,
                'total'=>$total
            ]);
        }else{
            return json([
                'code'=>$this->code['success'],
                'msg'=>'查询失败',
            ]);
        }

    }

    /**
     * 显示创建资源表单页.
     *
     * @return \think\Response
     */
    public function create()
    {
        //
    }

    /**
     * 保存新建的资源
     *
     * @param  \think\Request  $request
     * @return \think\Response
     */
    public function save(Request $request)
    {
        //
        $data=$this->request->post();
        $data['ctime']=time();
//        $flag=validate("Stayhome")->scene()->check($data);
//        if(!$flag){
//            return json([
//                'code'=>$this->code['error'],
//                'msg'=>'验证失败',
//            ]);
//        };
        $isExit=Db::table("stayhome")->where("sname",$data["sname"])->count();
        if($isExit){
            return json([
                'code'=>$this->code['error'],
                'msg'=>'该民宿名称已存在',
            ]);
        }
        $result=Db::table("stayhome")->insert($data);
        if($result){
            return json([
                'code'=>$this->code['success'],
                'msg'=>'数据插入成功',
            ]);
        }else{
            return json([
                'code'=>$this->code['error'],
                'msg'=>'数据插入失败',
            ]);
        }
    }

    /**
     * 显示指定的资源
     *
     * @param  int  $id
     * @return \think\Response
     */
    public function read($id)
    {
        //
        $sid=$id;
        $result=Db::table("stayhome")->where('sid',$sid)->find();
        if($result){
            $result['sbanner1']=explode(",",$result['sbanner']) ;
            return json([
                'code'=>$this->code['success'],
                'msg'=>'查询成功',
                'data'=>$result
            ]);
        }else{
            return json([
                'code'=>$this->code['error'],
                'msg'=>'查询失败',
            ]);
        }

    }

    /**
     * 显示编辑资源表单页.
     *
     * @param  int  $id
     * @return \think\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * 保存更新的资源
     *
     * @param  \think\Request  $request
     * @param  int  $id
     * @return \think\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * 删除指定资源
     *
     * @param  int  $id
     * @return \think\Response
     */
    public function delete($id)
    {
        //
    }
}
